### ISSUE TITLE
Can't install on Android 11

### ISSUE THREAD

**Issue by baklim** [niks255/FairEmail#1]
# Bug report

* Did you check if there wasn't a similar bug report? yes
* Are you using the [latest version](https://github.com/M66B/FairEmail/releases) of the app? yes

## Expected behavior
Application installed

## Actual behavior
com.android.server.pm.PackageManagerException: No signature found in package of version 2 or newer for package eu.faircode.email

## Steps to reproduce the problem

1. Install apk with PackageManager

## Version

* App version: 1.456
* Android version: 11

P.S.: https://stackoverflow.com/questions/64364407/app-not-installing-in-android-11-but-works-on-previous-versions

**Comment by niks255** [comment]
Okay, seems like signature V2 is required now.
I'll fix this in the next build. Thanks.

**Comment by lamyergeier** [comment]
@niks255 I could not install the latest release. I am on Android 11, which of the 5 apk files in the release do I need to install?

**Comment by niks255** [comment]
> @niks255 I could not install the latest release. I am on Android 11, which of the 5 apk files in the release do I need to install?

If you have no idea, just install a universal one. That's why it exists.
What's the error that you're getting?

**Comment by lamyergeier** [comment]
@niks255  I tried installing universal release also, it says app not installed. May I ask how is it different than the official release?

**Comment by niks255** [comment]
> @niks255 I tried installing universal release also, it says app not installed. May I ask how is it different than the official release?

Of course it is, it has a different signature. If you have an official one installed, you should uninstall it before installing my builds
