### ISSUE TITLE
NetGuard fork

### ISSUE THREAD

**Issue by DI555** [niks255/FairEmail#10]
As i see you making forks especially for self using, could you please and fork NetGuard either? (..i mean the same way - not to ne appeared in "forks" list there, but the licence is letting it of course)
Great thank you in advance!!!

**Comment by niks255** [comment]
Usually I fork and build stuff that I personally use and I do not use NetGuard
I'm pretty sure forks already exist, you just need to look them up

**Comment by DI555** [comment]
Unfortunately no, are no live normal forks there(( i thought you might like using a good firewall that defend from any leaks of android os and services either, even though if are using all opensourced apps.
But NetGuard with it is quite small in amount of data, so may be you’ll try it and would like to fork 👍👍👍.

**Comment by niks255** [comment]
> Unfortunately no, are no live normal forks there(( i thought you might like using a good firewall that defend from any leaks of android os and services either, even though if are using all opensourced apps. But NetGuard with it is quite small in amount of data, so may be you’ll try it and would like to fork 👍👍👍.

Well, here you go https://github.com/niks255/NetGuard/releases
