### ISSUE TITLE
Remove Bugsnag and Google Billing

### ISSUE THREAD

**Issue by asakura42** [niks255/FairEmail#2]
Sources have unneeded Bugsnag and Google Billing features, atavisms from original app version. I propose to delete these lines (but don't know how myself, or I'd already send PR)

**Comment by niks255** [comment]
Google billing is only for playstore builds, it is not included in github builds of the app - neither original nor mine. 

Removing bugsnag is pointless, since it is an open-source library and reports are turned off by default.

**Comment by asakura42** [comment]
Thanks for the answer.
