### ISSUE TITLE
App unavailable on playstore

### ISSUE THREAD

**Issue by filipepcapulo** [niks255/FairEmail#3]
Hi.

The app do not appear in the playstore search for Brazil and the link https://play.google.com/store/apps/details?id=eu.faircode.email return the follow message: "O URL solicitado não foi encontrado no servidor."

The app will be available on playstore again?

**Comment by niks255** [comment]
Hey.
This is a fork of the app, I am not the original developer. This is the original repository https://github.com/M66B/FairEmail
