### ISSUE TITLE
无法登录163账号

### ISSUE THREAD

**Issue by biange200** [niks255/FairEmail#5]
网易163邮箱账号无法登录了![Screenshot_20220902_130456.jpg](https://user-images.githubusercontent.com/37582806/188063488-c7e58305-fbfc-4982-a37d-8bc43fd9c02f.jpg)

**Comment by niks255** [comment]
Check account settings, maybe IMAP is disabled by default.
Anyway, I am not the original developer of the app, nor do I pretend to be. You should go and ask the developer himself https://github.com/M66B/FairEmail
