### ISSUE TITLE
Will FairEmail ever get "search-in-page"\"find-in-page"? CTRL-F doesn't bring up any kind of search, and clicking the search icon only shows which email a word was found in, not what line it is on.

### ISSUE THREAD

**Issue by ETERNALBLUEbullrun** [niks255/FairEmail#6]
Will FairEmail ever get "search-in-page"\"find-in-page"? CTRL-F doesn't bring up any kind of search, and clicking the search icon only shows which email a word was found in, not what line it is on.

**Comment by niks255** [comment]
I don't know, ask the developer. This is a fork, not the original.
