### ISSUE TITLE
Export Import Settings Disappeared!

### ISSUE THREAD

**Issue by lamyergeier** [niks255/FairEmail#7]
# Question

* For questions, please use [this forum](https://forum.xda-developers.com/android/apps-games/source-email-t3824168).

# Feature request

* Did you check if there wasn't a similar feature request? Yes
* Did you read [the FAQ](https://github.com/M66B/FairEmail/blob/master/FAQ.md)? Yes

# Bug report

* Did you check if there wasn't a similar bug report?
* Are you using the [latest version](https://github.com/M66B/FairEmail/releases) of the app?

## Expected behavior

Export Import Settings Disappeared from latest version, see attached image below

## Actual behavior

Export Import Settings present in version 1.2019, see attached image below

## Steps to reproduce the problem

1.
1.
1.

## Version

* App version: mentioned in the attached image
* Android version: 13
* Downloaded from: Github Niks255

Latest Version

![image](https://user-images.githubusercontent.com/42092626/215060338-1d80327e-c03f-46ba-8422-d8eb88d5da90.png)

---

Version: 1.2019

![image](https://user-images.githubusercontent.com/42092626/215060965-5f392257-adc7-4d36-be0c-ba556cdbefb1.png)

**Comment by niks255** [comment]
It did not disappear, the developer just moved it to settings to a dedicated backup page since he introduced a cloud backup feature.
