### ISSUE TITLE
Is the fork stopped updating? 

### ISSUE THREAD

**Issue by lamyergeier** [niks255/FairEmail#8]
# Question

Is the fork stopped updating? All recent release show same commit number. 

* For questions, please use [this forum](https://forum.xda-developers.com/android/apps-games/source-email-t3824168).

# Feature request

* Did you check if there wasn't a similar feature request?
* Did you read [the FAQ](https://github.com/M66B/FairEmail/blob/master/FAQ.md)?

# Bug report

* Did you check if there wasn't a similar bug report?
* Are you using the [latest version](https://github.com/M66B/FairEmail/releases) of the app?

## Steps to reproduce the problem

1.
1.
1.

## Version

* App version:
* Android version:
* Downloaded from:

**Comment by niks255** [comment]
No, I just forgot to push changes as usual. 
Looks like I screwed up a bit. Thanks for reporting.
