### ISSUE TITLE
No Update?

### ISSUE THREAD

**Issue by Twizzer** [niks255/FairEmail#9]
I'm inquiring if this branch is still getting updated against the primary branch?

**Comment by niks255** [comment]
Yes it does, I just skip a few versions because the upstream releases come out way too often. But it's still maintained and updated every few weeks or so.

**Comment by Twizzer** [comment]
Can you set it to not try to Playstore check/update.

**Comment by niks255** [comment]
> Can you set it to not try to Playstore check/update.

If it shows up in your play store updates, I'm afraid there's not much that I can do. It's a new stupid play store feature to show updates for apps regardless of package signature.

I would suggest turning play store auto updates on and then excluding FairEmail from automatic updates https://support.google.com/googleplay/answer/113412

If you dislike automatic updates, you could use Aurora Store to update apps manually https://aurorastore.org/
It's an unofficial alternative and FOSS play store client that doesn't show you updates for apps that have a different signature.
